#!/usr/bin/env bash

#############################################################################
#                                                                           #
# Copyright (C) 2010 Rafael Fernández López <ereslibre@kde.org>             #
# Copyright (C) 2010 UFO Coders <info@ufocoders.com>                        #
#                                                                           #
# This file is distributed with the same license and terms as libbluedevil. #
#                                                                           #
#############################################################################

doxygen --version &> /dev/null

if [ $? -ne 0 ]; then
	echo "!!! Doxygen not installed. Please install it in order to generate documentation"
	exit 1
fi

rm -rf doc &> /dev/null
doxygen .doxyfile &> /dev/null

if [ $? -eq 0 ]; then
	echo "*** Documentation has been correctly generated under 'doc' directory"
	exit 0
fi

echo "!!! Documentation could not be generated due to an error"
exit 2
